### ISSUE TITLE
Doesn't seem to work on Kodi 17

### ISSUE THREAD

**Issue by mbuhler** [lwille/plugin.video.udemy#2]
Not sure if this code is complete or not, but it doesn't seem to work on Kodi v 17.    It logs in and loads the classes that you own just fine but I fails when trying to play them.  There is a message about logging in every time you try to hit play, so maybe it's an authentication issue?

**Comment by lwille** [comment]
Hi @mbuhler, you're right - this is far from complete, and I must admit I temporarily discontinued the project. I hadn't even pushed the latest commit which kind of worked back then (despite the obvious FORBIDDEN errors which might be related to your issue), but now even produces crashes when running it :thinking:

I've been developing against Kodi 15.2 since that's is the "official" version for Ubuntu 16.04, but as I'm using [xmbcswift2](https://github.com/jbeluch/xbmcswift2) it should be generally compatible with v17.

If you want to do some debugging yourself, I can recommend the [xmbcswift2 command line](https://github.com/jbeluch/xbmcswift2/blob/master/docs/commandline.rst) tool.

Let me know how the latest commit behaves on your Kodi and paste some logs - as I said, it's working on the command line, but will probably crash your Kodi, so it need some thorough debugging :)

**Comment by BlackHeart-TF** [comment]
the play functions is.. well.. empty lol
I've been working on it though, should be done in the near future :D

**Comment by raoulbhatia** [comment]
Any update? Looking forward to trying this out in Kodi-18.0!

**Comment by mk2301** [comment]
Are you able to send authenticated requests to the API using PostMan or tools like that? What ever I tried, I always get permission denied, even when I tried to just list the courses sending the same headers as the plugin and the cookie. Maybe it's just the limitation you get when trying to trick the API authentication without obtaining a client key from Udemy.

However, here is my log on Kodi 17.1 on an Odroid C2 running LibreELEC:

<pre>
16:54:27.519 T:545980936416  NOTICE: [xbmcswift2] Request for "/course/756150/play/6655594" matches rule for function "play"
16:54:27.922 T:545980936416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 403 Client Error: FORBIDDEN for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/756150/lectures/6655594?fields%5Basset%5D=@min,download_urls,external_url,slide_urls&fields%5Bcourse%5D=id,is_paid,url&fields%5Blecture%5D=@default,view_html,course&page_config=ct_v4&tracking_tag=ctp_lecture
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.udemy/addon.py", line 152, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.udemy/addon.py", line 96, in play
                                                params='fields%5Basset%5D=@min,download_urls,external_url,slide_urls&fields%5Bcourse%5D=id,is_paid,url&fields%5Blecture%5D=@default,view_html,course&page_config=ct_v4&tracking_tag=ctp_lecture')
                                              File "/storage/.kodi/addons/plugin.video.udemy/addon.py", line 75, in load_json
                                                r.raise_for_status()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 893, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 403 Client Error: FORBIDDEN for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/756150/lectures/6655594?fields%5Basset%5D=@min,download_urls,external_url,slide_urls&fields%5Bcourse%5D=id,is_paid,url&fields%5Blecture%5D=@default,view_html,course&page_config=ct_v4&tracking_tag=ctp_lecture
                                            -->End of Python script error report<--
16:54:28.121 T:548474925056   ERROR: GetDirectory - Error getting plugin://plugin.video.udemy/course/756150/play/6655594
16:54:28.122 T:548474925056   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.udemy/course/756150/play/6655594) failed
</pre>

I hope someone can fix this soon

**Comment by BlackHeart-TF** [comment]
im not getting any errors, its just not showing some of the information. like the iOS app sends a request and gets a video link. I send an identical request from Kodi and it does return video info but without the video link :/

**Comment by mk2301** [comment]
@ShadowNoire have you explicitely requested the field for the link?

**Comment by BlackHeart-TF** [comment]
@mk2301 yes, literally the exact string copy & pasted and got a different result which to me, seems like its some kind of auth issue

**Comment by exxmen** [comment]
any luck on this guys?? would love to help but I'm just starting to learn python

**Comment by BlackHeart-TF** [comment]
@exxmen I haven't really been on it lately. just finished a project though so might pick it up again

**Comment by zag2me** [comment]
Thanks that fork commit fixes it for me. Great work.
