### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by matthuisman** [lwille/plugin.video.udemy#9]
Hi there,

Just wanted to say thanks for your work on this!
I have created my add-on and used this as a basis for the initial API calls.

After a bit more hunting and decompiling  their android app, I have found a few more "correct" calls that make talking to their API a bit nicer (eg. no csrf)
It instead uses their official auth token initially to then create the users token.

Anyway, feel free to check it out and use any code that might be useful for your addon.

Source:
https://github.com/matthuisman/plugin.video.udemy

Release Post:
https://www.matthuisman.nz/2018/08/udemy-kodi-add-on.html

Addon zip download:
https://github.com/matthuisman/kodi-repo/raw/master/plugin.video.udemy/plugin.video.udemy-latest.zip

Thanks again,

Matt

**Comment by lwille** [comment]
Thank you for the good work @matthuisman!
Very good idea to fetch the token instead of storing the password, also your plugin structure looks quite mature.

As this was my first shot at a Kodi plugin and served its purpose as an evening project, I gladly forward everyone to use your repository.
